version: '3.5'
services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:7.2-alpine
    command: redis-server
    ports:
      - 6379
    volumes:
      - ./tmp/redis:/var/lib/redis/data
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/e-commerce-rails-7
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    stdin_open: true
    tty: true

volumes:
  redis:
  postgres:
